import sogang from "../../assets/images/sogang_logo.png";

const arr = [
  {
    text: "기유림 | 총괄 기획",
    span: 3,
    top: 5,
    left: 0,
    rotate: 10,
    src: "../../assets/images/유림.png",
  },
  { text: "류지원 | 총괄 기획", span: 3, top: -5, left: 0, rotate: 3, src: "" },
  { text: "임서영 | 아카이빙", span: 2, top: 10, left: 0, rotate: 0, src: "" },
  { text: "김지원 | 디자인", span: 2, top: 30, left: 0, rotate: -34, src: "" },
  {
    text: "류민우 | 프로그램 기획",
    span: 2,
    top: 0,
    left: 0,
    rotate: 0,
    src: "",
  },
  { text: "임이서 | 제작부", span: 2, top: 0, left: 0, rotate: 0, src: "" },
  { text: "이연우 | 아이디어팀", span: 2, top: 0, left: 0, rotate: 0, src: "" },
  {
    text: "정고은 | 아카이빙 | 웹",
    span: 2,
    top: 0,
    left: 0,
    rotate: 0,
    src: "",
  },
  {
    text: "채경서 | 프로그램기획",
    span: 2,
    top: 0,
    left: 0,
    rotate: 0,
    src: "",
  },
  { text: "윤근우 | 전시 기획", span: 2, top: 0, left: 0, rotate: 0, src: "" },
  {
    text: "조성효 | 프로그램 기획",
    span: 2,
    top: 0,
    left: 0,
    rotate: 0,
    src: "",
  },
  { text: "김준수 | 디자인", span: 2, top: 0, left: 0, rotate: 0, src: "" },
  {
    text: "김성민 | 작가협력 팀",
    span: 2,
    top: 0,
    left: 0,
    rotate: 0,
    src: "",
  },
  { text: "신현주 | 전시 기획", span: 2, top: 0, left: 0, rotate: 0, src: "" },
  {
    text: "이창호 | 작가협력 팀",
    span: 2,
    top: 0,
    left: 0,
    rotate: 0,
    src: "",
  },
  {
    text: "금유현 | 디자인 | 아카이빙",
    span: 2,
    top: 0,
    left: 0,
    rotate: 0,
    src: "",
  },
  { text: "형화진 | 제작부", span: 2, top: 0, left: 0, rotate: 0, src: "" },
  {
    text: "안현석 | 아카이빙 | 웹",
    span: 3,
    top: 0,
    left: 0,
    rotate: 0,
    src: "",
  },
  { text: "장한슬 | 아이디어", span: 3, top: 0, left: 0, rotate: 0, src: "" },
];

export default arr;
